name: Build EXE

on:
  push:
    branches: [ master ]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install BAT to EXE Converter
        run: |
          curl -LJO "https://sourceforge.net/projects/battoexe/files/latest/download"
          tar -xf "download" --strip-components=1

      - name: Convert CMD to EXE
        run: .\battoexeconverter.bat -bat file.cmd -exe file.exe -icon file.ico

      - name: Upload EXE file
        uses: actions/upload-artifact@v2
        with:
          name: file.exe
          path: file.exe